import { useEffect, useState, type FormEvent } from 'react';
import { apiFetch } from '../../services/api';

type Media = { title: string; url: string };
export default function AddMediaModal({ roomCode, onClose, onAdd }: { roomCode: string; onClose: () => void; onAdd: (media: Media) => void }) {
  const [title, setTitle] = useState(''); const [file, setFile] = useState<File | null>(null); const [error, setError] = useState(''); const [uploading, setUploading] = useState(false); const [elapsed, setElapsed] = useState(0);
  useEffect(() => { if (!uploading) return; const started = Date.now(); const timer = window.setInterval(() => setElapsed(Math.floor((Date.now() - started) / 1000)), 1000); return () => window.clearInterval(timer); }, [uploading]);
  async function submit(event: FormEvent) { event.preventDefault(); if (!file) { setError('Choose a video file.'); return; } setUploading(true); try { const body = new FormData(); body.append('video', file); if (title.trim()) body.append('title', title.trim()); const response = await apiFetch(`/rooms/${roomCode}/media`, { method: 'POST', body }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Video processing failed.'); const apiRoot = (import.meta.env.VITE_API_URL || 'http://localhost:5000/api').replace(/\/$/, ''); onAdd({ title: data.media.title, url: `${apiRoot}${data.media.url.replace(/^\/api/, '')}` }); onClose(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Upload failed.'); } finally { setUploading(false); } }
  const clock = `${String(Math.floor(elapsed / 60)).padStart(2, '0')}:${String(elapsed % 60).padStart(2, '0')}`;
  return <div className="modal-overlay" role="dialog" aria-modal="true" aria-labelledby="add-media-title"><div className="modal"><div className="modal-header"><h2 id="add-media-title" className="modal-title">Add video</h2><button className="modal-close" onClick={onClose} aria-label="Close" disabled={uploading}>×</button></div><div className="modal-body"><form onSubmit={submit}><div className="form-group mb-4"><label htmlFor="mediaFile" className="form-label">Video file</label><input id="mediaFile" className="form-input" type="file" accept="video/*" disabled={uploading} onChange={event => { setFile(event.target.files?.[0] || null); setError(''); }} /></div><div className="form-group mb-4"><label htmlFor="mediaTitle" className="form-label">Title <span>(optional)</span></label><input id="mediaTitle" className="form-input" placeholder="Tonight's watch" value={title} disabled={uploading} onChange={event => setTitle(event.target.value)} /></div>{uploading && <div className="media-progress" role="status"><span className="media-spinner" /><span>Uploading and converting · {clock}<small>Large files and Dolby audio can take a few minutes.</small></span></div>}{error && <p className="form-error">{error}</p>}<div className="flex gap-2 justify-end"><button type="button" className="btn btn-secondary" onClick={onClose} disabled={uploading}>Cancel</button><button type="submit" className="btn btn-primary" disabled={uploading}>{uploading ? 'Processing…' : 'Add video'}</button></div></form></div></div></div>;
}
